# Generated by Django 4.1.2 on 2022-10-25 11:18

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('photo_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('album_id', models.IntegerField()),
                ('dominant_color', models.CharField(max_length=7)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to=images.models.user_directory_path, width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
