# Generated by Django 4.1.2 on 2022-10-25 12:02

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='dominant_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(height_field='height', upload_to=images.models.user_directory_path, width_field='width'),
        ),
    ]
