# Generated by Django 4.1.2 on 2022-10-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_images_dominant_color_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='dominant_color',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
