# Generated by Django 4.1.2 on 2022-10-26 16:58

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_images_dominant_color_alter_images_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=images.models.user_directory_path, width_field='width'),
        ),
    ]
